# Generated by Django 3.1.1 on 2021-04-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0039_auto_20210412_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_operator', models.CharField(choices=[('>', '>'), ('>=', '>='), ('=', '='), ('<', '<'), ('<=', '<=')], default='=', max_length=2)),
                ('period_operator', models.CharField(choices=[('sum', 'sum'), ('average', 'average'), ('max', 'max')], default='sum', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.client')),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
            bases=('priority_action.priorityaction',),
        ),
        migrations.CreateModel(
            name='CorrelationChange',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('priority_action.priorityaction',),
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.IntegerField(default=0)),
            ],
            bases=('priority_action.priorityaction',),
        ),
        migrations.CreateModel(
            name='IntentChange',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('priority_action.priorityaction',),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.IntegerField(default=0)),
            ],
            bases=('priority_action.priorityaction',),
        ),
        migrations.CreateModel(
            name='SalesChange',
            fields=[
                ('priorityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='priority_action.priorityaction')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('priority_action.priorityaction',),
        ),
    ]
