# Generated by Django 3.1.1 on 2021-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_method', models.CharField(choices=[('internal_tool', 'Internal Tool'), ('wayback_machine', 'WayBack Machine'), ('default', 'Default')], default='default', max_length=20)),
                ('number_of_urls', models.PositiveIntegerField(default=15, help_text='Number urls to archive per request, max: 20')),
            ],
        ),
    ]
