# Generated by Django 3.0.8 on 2020-10-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_annotatorqueue_client_country_knownurls'),
        ('users', '0004_auto_20201007_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.AnnotatorQueue'),
        ),
    ]
