# Generated by Django 3.1.1 on 2020-11-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201027_0442'),
        ('users', '0006_auto_20201020_1345'),
    ]

    operations = [
    ]
