# Generated by Django 3.1.1 on 2021-04-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0039_auto_20210412_1707'),
        ('users', '0008_auto_20210412_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('is_admin', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.client')),
            ],
        ),
    ]
