# Generated by Django 3.1.1 on 2021-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('developer', 'developer'), ('annotator', 'annotator'), ('manager', 'manager'), ('machine', 'machine'), ('client', 'client')], max_length=12),
        ),
    ]
