# Generated by Django 3.1.1 on 2021-04-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210422_0930'),
        ('users', '0011_auto_20210421_1639'),
    ]

    operations = [
    ]
