# Generated by Django 3.1.1 on 2021-04-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20210422_1127'),
        ('users', '0011_auto_20210421_0922'),
    ]

    operations = [
    ]
