# Generated by Django 3.1.1 on 2021-02-09 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admintool', '0002_auto_20201221_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastatus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
