# Generated by Django 3.1.1 on 2020-10-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='label',
            new_name='title',
        ),
    ]
