# Generated by Django 3.1.1 on 2020-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20201017_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeFacetRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_facet', models.CharField(max_length=10)),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_relations', to='classification.facet')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_relations', to='classification.node')),
            ],
        ),
        migrations.AddField(
            model_name='facet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facets', to='classification.facetcategory'),
        ),

        migrations.RemoveField(
            model_name='node',
            name='facets',
        ),
        migrations.AddField(
            model_name='node',
            name='facets',
            field=models.ManyToManyField(through='classification.NodeFacetRelationship', to='classification.Facet'),
        ),
    ]
