# Generated by Django 3.1.1 on 2020-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_auto_20201020_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefacetrelationship',
            name='has_facet',
            field=models.CharField(choices=[('always', 'always'), ('sometimes', 'sometimes'), ('never', 'never')], max_length=10),
        ),
    ]
