# Generated by Django 3.1.1 on 2020-10-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_annotationstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotationStats',
        ),
        migrations.CreateModel(
            name='HierarchyEditor',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Hierarchy Editor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classification.node',),
        ),
    ]
