# Generated by Django 3.1.1 on 2020-10-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20201020_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefacetrelationship',
            name='facet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_nodes', to='classification.facet'),
        ),
        migrations.AlterField(
            model_name='nodefacetrelationship',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_properties', to='classification.node'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('title', 'parent')},
        ),
    ]
