# Generated by Django 3.1.1 on 2020-11-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20201029_0242'),
        ('classification', '0006_facet_description'),
    ]

    operations = [
    ]
