# Generated by Django 3.1.1 on 2020-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0007_merge_20201103_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierachyJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
