# Generated by Django 3.1.1 on 2020-11-06 17:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('classification', '0007_merge_20201103_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facet',
            new_name='FacetValue',
        ),
        migrations.AlterModelOptions(
            name='facetcategory',
            options={'verbose_name_plural': 'Facet Categories'},
        ),
    ]
