# Generated by Django 3.1.1 on 2020-11-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0008_hierachyjson'),
        ('classification', '0008_auto_20201106_1832'),
    ]

    operations = [
    ]
