# Generated by Django 3.1.1 on 2020-11-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0009_merge_20201107_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierachyjson',
            options={'ordering': ['-timestamp']},
        ),
    ]
