# Generated by Django 3.1.1 on 2020-11-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0010_auto_20201122_0753'),
        ('classification', '0010_auto_20201119_0839'),
    ]

    operations = [
    ]
