# Generated by Django 3.1.1 on 2020-12-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0011_merge_20201124_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facetcategory',
            options={'ordering': ('title',), 'verbose_name_plural': 'Facet Categories'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('title',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='facetvalue',
            order_with_respect_to='category',
        ),
    ]
