# Generated by Django 3.1.1 on 2021-01-20 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0012_auto_20201209_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 20, 7, 56, 57, 27999, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facetvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 20, 7, 57, 2, 357715, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facetvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 20, 7, 57, 10, 9610, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nodefacetrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 20, 7, 57, 17, 13164, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodefacetrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
