# Generated by Django 3.1.1 on 2021-01-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0013_auto_20210120_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facetvalue',
            options={'ordering': ('category', 'label')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='facetvalue',
            order_with_respect_to=None,
        ),
    ]
