# Generated by Django 3.1.1 on 2021-01-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0014_auto_20210120_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HierarchyEditor',
        ),
        migrations.CreateModel(
            name='TaxonomyEditor',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Taxonomy Editor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classification.node',),
        ),
    ]
