# Generated by Django 3.1.1 on 2021-03-03 16:47

from django.db import migrations


def change_to_uppercase(apps, schema_editor):
    """
    Modifying all FacetValues and FacetCategory object names to 
    uppercase 
    """    
    FacetCategory = apps.get_model('classification', 'FacetCategory')
    FacetValue = apps.get_model('classification', 'FacetValue')

    for obj in FacetCategory.objects.all():
        obj.title = obj.title.upper()
        obj.save()
    
    for obj in FacetValue.objects.all():
        obj.label = obj.label.upper()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0015_auto_20210121_1544'),
    ]

    operations = [
        migrations.RunPython(change_to_uppercase)
    ]
