# Generated by Django 3.1.1 on 2021-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0015_auto_20210121_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'is deleted')], default='active', max_length=50),
        ),
    ]
