# Generated by Django 3.1.1 on 2021-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0015_auto_20210121_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetcategory',
            name='facet_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Select'), ('multi', 'Multi-Select'), ('boolean', 'Truth or Falsity')], default='single', max_length=100),
        ),
    ]
