# Generated by Django 3.1.1 on 2021-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0016_standardize_facetvalue_and_facetcategory_names'),
        ('classification', '0016_facetcategory_facet_type'),
    ]

    operations = [
    ]
