# Generated by Django 3.1.1 on 2021-03-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0016_node_status'),
        ('classification', '0019_auto_20210309_1719'),
    ]

    operations = [
    ]
