# Generated by Django 3.1.1 on 2021-03-12 11:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0020_merge_20210311_1433'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='node',
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
