# Generated by Django 3.1.1 on 2021-03-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0021_auto_20210312_1206'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='node',
            managers=[
            ],
        ),
    ]
