# Generated by Django 3.1.1 on 2021-03-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0021_auto_20210312_0751'),
        ('classification', '0022_auto_20210312_1212'),
    ]

    operations = [
    ]
