# Generated by Django 3.1.1 on 2021-04-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0023_merge_20210316_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('title', 'parent', 'status')},
        ),
    ]
