# Generated by Django 3.1.1 on 2021-05-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0043_task_reason_for_skipping_url'),
        ('classification', '0024_auto_20210414_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SKUMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('sku_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('hierarchy_mapping', models.CharField(blank=True, help_text='node hierarchy data', max_length=200, null=True)),
                ('product_name_variation', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_quantity', models.IntegerField(blank=True, default=0)),
                ('sales_value', models.IntegerField(blank=True, default=0)),
                ('last_sale', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.client')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
