# Generated by Django 3.1.1 on 2021-05-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0025_historicalnode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalNode',
        ),
    ]
