# Generated by Django 3.1.1 on 2021-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0028_historicalfacetcategory_historicalfacetvalue_historicalnodefacetrelationship'),
        ('classification', '0025_manufacturer_skumapper'),
    ]

    operations = [
    ]
