# Generated by Django 3.1.1 on 2021-06-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0029_merge_20210527_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skumapper',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skumapper',
            name='hierarchy_mapping',
            field=models.ForeignKey(help_text='node hierarchy data', null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.node'),
        ),
        migrations.AlterField(
            model_name='skumapper',
            name='product_name_variation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
