# Generated by Django 3.1.1 on 2021-06-11 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0030_auto_20210602_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='hierarchy',
            field=models.JSONField(null=True),
        ),
    ]
