# Generated by Django 3.1.1 on 2021-06-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0030_auto_20210602_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUMapperEditor',
            fields=[
            ],
            options={
                'verbose_name': 'SKU Mapper Editor',
                'verbose_name_plural': 'SKU Mapper Editor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classification.skumapper',),
        ),
        migrations.AlterField(
            model_name='skumapper',
            name='hierarchy_mapping',
            field=models.ForeignKey(blank=True, help_text='node hierarchy data', null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.node'),
        ),
    ]
