# Generated by Django 3.1.1 on 2021-06-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0031_auto_20210611_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyChangeFeed',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Taxonomy Change Feed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classification.node',),
        ),
    ]
