# Generated by Django 3.1.1 on 2021-06-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0031_auto_20210609_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skumapper',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.manufacturer'),
        ),
    ]
