# Generated by Django 3.1.1 on 2021-06-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0032_taxonomychangefeed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomychangefeed',
            options={},
        ),
    ]
