# Generated by Django 3.1.1 on 2021-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0032_auto_20210614_1357'),
        ('classification', '0032_auto_20210615_1034'),
    ]

    operations = [
    ]
