# Generated by Django 3.1.1 on 2021-06-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0032_auto_20210615_1034'),
        ('classification', '0031_auto_20210611_1524'),
    ]

    operations = [
    ]
