# Generated by Django 3.1.1 on 2021-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0033_auto_20210617_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomychangefeed',
            options={'verbose_name_plural': 'Taxonomy Change Feed'},
        ),
    ]
