# Generated by Django 3.1.1 on 2021-06-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0034_auto_20210617_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxonomyChangeFeed',
        ),
        migrations.CreateModel(
            name='TaxonomyFeed',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Taxonomy Feed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classification.node',),
        ),
    ]
