# Generated by Django 3.1.1 on 2021-06-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0033_merge_20210617_1256'),
        ('classification', '0033_merge_20210617_1546'),
        ('classification', '0035_auto_20210617_2001'),
    ]

    operations = [
    ]
