# Generated by Django 3.0.8 on 2020-08-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20200714_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainpriority',
            options={'ordering': ['views'], 'verbose_name_plural': 'Domain Priority Queue'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['priority', 'page_views']},
        ),
        migrations.AddField(
            model_name='url',
            name='priority',
            field=models.IntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'low')], default=2),
        ),
        migrations.AlterField(
            model_name='url',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.DomainPriority'),
        ),
    ]
