# Generated by Django 3.0.8 on 2020-08-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20200803_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['priority', '-page_views']},
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='annotation.Url'),
        ),
        migrations.CreateModel(
            name='IntentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('subset', models.CharField(blank=True, max_length=100, null=True)),
                ('intent', models.IntegerField()),
                ('date_processed', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_data', to='annotation.Url')),
            ],
            options={
                'verbose_name_plural': 'Intent Data',
                'db_table': 'intent_data',
                'ordering': ['-date_processed'],
            },
        ),
    ]
