# Generated by Django 3.0.8 on 2020-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('annotation', '0004_auto_20200826_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationStats',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Annotation Scoreboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='ArchiveQueue',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Archive Queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.url',),
        ),
        migrations.CreateModel(
            name='BadUrl',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Bad Urls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.url',),
        ),
        migrations.CreateModel(
            name='RawUrl',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Raw URLs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.url',),
        ),
        migrations.CreateModel(
            name='TBAQ',
            fields=[
            ],
            options={
                'verbose_name_plural': 'TBAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.url',),
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['time_submitted']},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['priority', '-page_views'], 'verbose_name_plural': 'All URLs'},
        ),
        migrations.AlterField(
            model_name='url',
            name='archived_url',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
    ]
