# Generated by Django 3.0.8 on 2020-09-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20200831_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivequeue',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'Archive Queue'},
        ),
        migrations.AlterModelOptions(
            name='badurl',
            options={'verbose_name': 'Bad Url', 'verbose_name_plural': 'Bad Urls'},
        ),
        migrations.AlterModelOptions(
            name='tbaq',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'TBAQ'},
        ),
        migrations.AddField(
            model_name='domainpriority',
            name='last_counted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['status'], name='urls_status_585954_idx'),
        ),
    ]
