# Generated by Django 3.1.1 on 2020-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_auto_20200915_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainpriority',
            options={'ordering': ['-views'], 'verbose_name_plural': 'Domain Priority Queue'},
        ),
        migrations.AlterField(
            model_name='url',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urls', to='annotation.domainpriority'),
        ),
    ]
