# Generated by Django 3.1.1 on 2020-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_auto_20200921_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archive_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
