# Generated by Django 3.0.8 on 2020-10-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('annotation', '0008_url_archive_attempt_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownUrls',
            fields=[
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Known Urls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.url',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('url', models.ManyToManyField(blank=True, to='annotation.Url')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.ManyToManyField(blank=True, to='annotation.Url')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatorQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
