# Generated by Django 3.0.8 on 2020-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_annotatorqueue_client_country_knownurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='url',
            new_name='urls',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='url',
            new_name='urls',
        ),
    ]
