# Generated by Django 3.0.8 on 2020-10-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_auto_20201014_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueUrlRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=50)),
                ('page_views', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Country')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Url')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='urls',
        ),
        migrations.AddField(
            model_name='client',
            name='urls',
            field=models.ManyToManyField(blank=True, through='annotation.QueueUrlRelationship', to='annotation.Url'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='urls',
        ),
        migrations.AddField(
            model_name='country',
            name='urls',
            field=models.ManyToManyField(blank=True, through='annotation.QueueUrlRelationship', to='annotation.Url'),
        ),
    ]
