# Generated by Django 3.0.8 on 2020-10-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_auto_20201016_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueurlrelationship',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.Client'),
        ),
        migrations.AlterField(
            model_name='queueurlrelationship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.Country'),
        ),
    ]
