# Generated by Django 3.1.1 on 2020-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_auto_20201016_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
