# Generated by Django 3.1.1 on 2020-11-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0013_auto_20201020_1349'),
        ('annotation', '0013_auto_20201028_1434'),
    ]

    operations = [
    ]
