# Generated by Django 3.1.1 on 2020-11-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0014_merge_20201102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomainrelationship',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.client'),
        ),
        migrations.AlterField(
            model_name='clientdomainrelationship',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.domainpriority'),
        ),
    ]
