# Generated by Django 3.1.1 on 2020-11-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_auto_20201106_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeswaxlist',
            name='greenlist_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beeswaxlist',
            name='redlist_id',
            field=models.IntegerField(null=True),
        ),
    ]
