# Generated by Django 3.1.1 on 2020-11-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_auto_20201111_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeswaxlist',
            name='greenlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beeswaxlist',
            name='redlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacetProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.CharField(max_length=100)),
                ('intent', models.IntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_properties', to='annotation.url')),
            ],
        ),
    ]
