# Generated by Django 3.1.1 on 2020-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_auto_20201111_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeswaxlist',
            name='greenlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beeswaxlist',
            name='redlist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
