# Generated by Django 3.1.1 on 2020-11-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_auto_20201122_1527'),
        ('annotation', '0017_auto_20201117_1519'),
    ]

    operations = [
    ]
