# Generated by Django 3.1.1 on 2020-11-24 12:31

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0019_merge_20201124_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentdata',
            old_name='intent',
            new_name='entity_intent',
        ),
        migrations.AddField(
            model_name='intentdata',
            name='facet_intent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intentdata',
            name='facets',
            field=models.JSONField(default=list),
        ),
    ]
