# Generated by Django 3.1.1 on 2020-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0023_auto_20201222_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlScraped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10485760, null=True)),
                ('url', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('scraped_vector', models.TextField(blank=True, null=True)),
                ('scraped_query', models.TextField(blank=True, null=True)),
                ('suggested_list', models.CharField(blank=True, max_length=30, null=True)),
                ('list_parsing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('instance_score', models.IntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('original_text', models.CharField(blank=True, max_length=10485760, null=True)),
            ],
            options={
                'db_table': 'urls_scraped',
            },
        ),
    ]
