# Generated by Django 3.1.1 on 2021-01-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0025_extensionversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('intent', models.IntegerField()),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='annotation.intentdata')),
            ],
        ),
        migrations.DeleteModel(
            name='DeniedUrl',
        ),
        migrations.AddField(
            model_name='facetproperty',
            name='facet_type',
            field=models.CharField(choices=[('default', 'default'), ('annotated', 'annotated')], default='annotated', max_length=10),
            preserve_default=False,
        ),
    ]
