# Generated by Django 3.1.1 on 2021-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0029_auto_20210130_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='queueurlrelationship',
            name='page_views',
        ),
    ]
