# Generated by Django 3.1.1 on 2021-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0030_auto_20210208_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTBAQ',
            fields=[
            ],
            options={
                'verbose_name_plural': 'New TBAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.queueurlrelationship',),
        ),
        migrations.RenameField(
            model_name='pageview',
            old_name='page_views',
            new_name='number_of_views',
        ),
        migrations.AddField(
            model_name='pageview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueurlrelationship',
            name='page_views',
            field=models.ManyToManyField(blank=True, to='annotation.PageView'),
        ),
    ]
