# Generated by Django 3.1.1 on 2021-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0031_auto_20210212_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueurlrelationship',
            name='date',
        ),
    ]
