# Generated by Django 3.1.1 on 2021-02-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0030_domainlog'),
        ('annotation', '0032_remove_queueurlrelationship_date'),
    ]

    operations = [
    ]
