# Generated by Django 3.1.1 on 2021-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0035_auto_20210309_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionversion',
            name='max_difference',
            field=models.CharField(default='0.3.0', help_text='Max difference between this version and the expected version for CE ', max_length=10),
        ),
    ]
