# Generated by Django 3.1.1 on 2021-03-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0036_extensionversion_max_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionversion',
            name='max_difference',
        ),
    ]
