# Generated by Django 3.1.1 on 2021-04-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0037_remove_extensionversion_max_difference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOverview',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.clientdomainrelationship',),
        ),
    ]
