# Generated by Django 3.1.1 on 2021-04-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0038_domainoverview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainoverview',
            options={'verbose_name_plural': 'Domain Overview'},
        ),
    ]
