# Generated by Django 3.1.1 on 2021-04-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0039_auto_20210412_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadUrl',
        ),
        migrations.CreateModel(
            name='SkippedUrl',
            fields=[
            ],
            options={
                'verbose_name': 'Skipped Url',
                'verbose_name_plural': 'Skipped Urls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('annotation.task',),
        ),
    ]
