# Generated by Django 3.1.1 on 2021-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0039_auto_20210412_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bigquery_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
