# Generated by Django 3.1.1 on 2021-04-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0040_auto_20210421_1656'),
        ('annotation', '0040_client_bigquery_table'),
    ]

    operations = [
    ]
