# Generated by Django 3.1.1 on 2021-04-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0041_merge_20210422_1048'),
        ('annotation', '0040_client_domain_name'),
    ]

    operations = [
    ]
