# Generated by Django 3.1.1 on 2021-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0042_merge_20210422_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reason_for_skipping_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
