# Generated by Django 3.1.1 on 2021-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0043_task_reason_for_skipping_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date_greenlisted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='greenlist_method',
            field=models.CharField(choices=[('manual', 'manual'), ('autofill', 'autofill'), ('scraper', 'scraper')], default='', max_length=100),
        ),
    ]
