# Generated by Django 3.1.1 on 2021-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0040_client_bigquery_table'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='countries',
            field=models.ManyToManyField(blank=True, to='annotation.Country'),
        ),
    ]
